export const content = {
  SancakSoft: {
    header: "SancakSoft",
    img: "/tfc.png",
    link: "https://tfaplatform.com/",
    desciription: [
      `/**`,
      `* Ekibimizde yer alan deneyimli yazılım geliştiriciler,`,
      "* müşterilerimizin ihtiyaçlarına özel çözümler üretmektedir.",
      "",
      "* Size özgü projeleriniz için en uygun programlama dillerini kullanarak,",
      "* geliştirmeniz gereken yazılımı oluşturabiliriz.",
      "* SancakSoft olarak, sizin ihtiyaçlarınızı ön planda tutuyoruz.",
      "*  Müşterilerimizi dinlemek ve anlamak için zaman ayırıyoruz. Bu sayede,",
      "* size en uygun çözümü sunabilmek için çalışıyoruz.",
      "",
      "* Profesyonel ve etkili yazılımların yanı sıra,",
      "* projelerinizi zamanında teslim etmek de bizim önceliğimizdir.",
      "* Bizimle çalıştığınızda, uzman bir yazılım geliştirme ekibiyle işbirliği yapacaksınız.",
      "* Projelerinizde sizinle yakından iletişim kurarak,",
      "* ihtiyaçlarınızı tam olarak anlayacak ve hedeflerinize ulaşmanıza yardımcı olacağız.",
      "*/",
      "",
      "",
    ],
  },
  "Ömer Yenidünya": {
    header: "Full Stack Blockchain Developer",
    img: "/tfc.png",
    link: "https://tfaplatform.com/",
    desciription: [
      `/**`,
      "* Ömer Yenidünya, iş dünyasında 15 yılı aşkın süredir faaliyet gösteren başarılı bir iş insanıdır.",
      "* Farklı sektörlerde gerçekleştirdiği başarılı projelerle ticari geçmişini ve deneyimini kanıtlamıştır.",
      "* Aynı zamanda bilgi güvenliği ve teknolojik ilerlemeler konularına büyük bir ilgi duymaktadır.",
      "* Ömer Yenidünya'nın hobileri arasında siber güvenlik ve teknoloji öncelikli yer tutmaktadır.",
      "*",
      "* Güncel trendleri takip eden ve yeniliklere açık bir vizyonu bulunması sayesinde",
      "* iş dünyasında güncel kalabilmekte ve yenilikleri yakalayabilmektedir.",
      "* Geleceğin teknolojilerini şekillendirme ve projelere değer katma konusunda",
      "* büyük bir heyecan ve tutkuyla sahiptir.",
      "*",
      "* Ömer Yenidünya, birikimleri ve tecrübelerinden",
      "* faydalanarak iş dünyasında liderlik rolünü başarıyla üstlenmektedir.",
      "*/",
      "",
      "",
    ],
  },
  "Serdar Kayacı": {
    header: "Full Stack Blockchain Developer",
    img: "/tfc.png",
    link: "https://tfaplatform.com/",
    desciription: [
      `/**`,
      "* Profesyonel ve deneyimli bir yazılım geliştirici olan Serdar, 7 yıl önce C# öğrenmeye",
      "* başladığı andan itibaren yazılım dünyasının büyüleyici cazibesine kendini bıraktı.",
      "* Bu başlangıç ona geniş bir yelpazede bilgi kazandırdı. Ardından, geniş",
      "* kullanım alanlarına sahip Python ve JavaScript dillerine yoğunlaştı,",
      "* yeteneklerini ve teknik bilgisini önemli ölçüde genişletti.",
      "*",
      "* 2018 yılında, artan potansiyeli ile dikkat çeken blockchain teknolojisinin",
      "* inceliklerine göz attı ve bu yenilikçi teknolojiye derinlemesine daldı.",
      "* Solidity, Rust, ReactJS ve NextJS gibi diller ve teknolojiler üzerine",
      "* yoğunlaştı ve bu alanda bir uzmanlık seviyesine ulaştı.",
      "* Bu süre zarfında, çeşitli iş fikirleri ve iş modellerinin kriptografik",
      "* tasarımı konusunda ciddi bir deneyim ve birikim elde etti.",
      "*",
      "* Şimdi, bir lider olarak hem girişimlere hem de büyük kuruluşlara danışmanlık hizmeti",
      "* vermektedir. Ayrıca, blockchain tabanlı modüller ve yapılar geliştirmekte olup,",
      "* teknoloji ve yazılım dünyasının sınırlarını zorlama arzusu ile",
      "* sürekli yenilikçi çözümler üretmeye yönelerek, geleceğin teknolojilerini için",
      "* büyük bir heyecan ve tutku duymaktadır.",
      "*/",
      "",
      "",
    ],
  },
  "Emre Kaya": {
    header: "Devops",
    img: "/tfc.png",
    link: "https://tfaplatform.com/",
    desciription: [
      `/**`,
      "* Emre Kaya, AWS'de çözüm mimarı olarak görev yapan bir profesyoneldir.",
      "* Kendisi, AWS hizmetlerinin mimari tasarımında uzmanlaşmıştır ve müşterilere optimize edilmiş,",
      "* güvenli ve ölçeklenebilir çözümler sunma konusunda deneyimlidir.",
      "*",
      "* DevOps süreçlerine hakim olan Emre Kaya, yazılım geliştirme",
      "* ve operasyonel süreçlerin entegrasyonunu sağlama konusunda uzmandır.",
      "* Docker konteyner teknolojisiyle ilgili derin bilgiye sahip olması,",
      "* uygulama dağıtımı ve altyapı yönetimi süreçlerini optimize etmede ona büyük avantaj sağlamaktadır.",
      "*",
      "* Emre Kaya aynı zamanda Golang programlama dilinde yeteneklidir ve bu dili kullanarak",
      "* etkili ve performans odaklı uygulamalar geliştirebilme becerisine sahiptir.",
      "*",
      "* Güvenlik konularına da büyük önem veren Emre Kaya, sistemlerin güvenliği",
      "* ve veri koruması için çözümler üretme konusunda uzmandır.",
      "* Siber güvenlik konusundaki bilgi birikimi, müşterilerin verilerinin ve sistemlerinin",
      "* güvende olmasını sağlama hedefine katkıda bulunmaktadır.",
      "*/",
      "",
      "",
    ],
  },
  "Burak Demir": {
    header: "Full Stack Blockchain Developer",
    img: "/tfc.png",
    link: "https://tfaplatform.com/",
    desciription: [
      `/**`,
      "* Burak Demir, C# programlama dilinde geniş bir bilgi birikimine ve deneyime sahiptir.",
      "* C#'ın sunduğu güçlü ve esnek özellikleri kullanarak",
      "* çeşitli projelerde başarılı sonuçlar elde etmiştir.",
      "* Kodlama ve yazılım mimarisi konularında derinlemesine bilgi sahibi olmasıyla,",
      "* uygulamaların güvenilir, hızlı ve ölçeklenebilir olmasını sağlamaktadır.",
      "*",
      "* Web servisleri konusundaki deneyimi, dağıtık uygulamaların geliştirilmesi",
      "* ve entegrasyonu konusunda ki bilgisi Burak Demir'i bu alanda yetenekli kılmaktadır.",
      "* RESTful veya SOAP tabanlı web servislerini tasarlama,",
      "* geliştirme ve entegrasyon konularında bilgi ve deneyime sahiptir.",
      "* İş süreçlerinin ve veri akışının etkili bir şekilde yönetilmesini",
      "* sağlamak için web servislerini kullanmaktadır.",
      "*",
      "* Burak Demir, C# dilindeki uzmanlığı ve sas sistemleri,",
      "* otomasyon sistemleri, web servisleri gibi alanlardaki deneyimiyle,",
      "* müşterilerin ihtiyaçlarını karşılayan, güvenilir ve ölçeklenebilir",
      "* yazılım çözümleri sunma konusunda başarılı bir şekilde görev almaktadır.",
      "*/",
      "",
      "",
    ],
  },
  "Ali Efe Öztürk": {
    header: "Frontend Developer",
    img: "/tfc.png",
    link: "https://tfaplatform.com/",
    desciription: [
      `/**`,
      "* Ali Efe Öztürk, frontend projelerinde kullanıcı deneyimini en üst düzeye çıkarmak",
      "* ve kullanıcı dostu arayüzler tasarlamak konusunda büyük bir yeteneğe sahiptir.",
      "* İleri düzeyde HTML, CSS ve JavaScript bilgisine sahip olmasıyla birlikte,",
      "* tasarım trendlerini takip ederek modern ve estetik web arayüzleri oluşturabilmektedir.",
      "*",
      "* Next.js ve React.js gibi popüler web dillerindeki derin bilgisi,",
      "* uygulamaların performansını ve ölçeklenebilirliğini artırmak için",
      "* optimize çözümler üretmesine yardımcı olmaktadır.",
      "* Proje süreçlerinde en iyi uygulamaları takip ederek,",
      "* kod kalitesini ve sürdürülebilirliği sağlama konusunda özen göstermektedir.",
      "*",
      "* Ali Efe Öztürk, frontend teknolojileri ve web dillerindeki ileri seviye bilgisiyle,",
      "* müşterilerin ihtiyaçlarına uygun, kullanıcı dostu ve etkileyici web uygulamaları",
      "* geliştirme konusunda başarıyla görev almaktadır.",
      "*/",
      "",
      "",
    ],
  },
  "Ayşe Ferda Yılmaz": {
    header: "Full Stack Developer",
    img: "/tfc.png",
    link: "https://tfaplatform.com/",
    desciription: [
      `/**`,
      "* Ayşe Ferda Yılmaz, özellikle Node.js, API'ler ve backend mimarileri",
      "* konusunda derin bir uzmanlığa sahip olan bir profesyoneldir.",
      "*",
      "* Node.js platformunu etkin bir şekilde kullanarak, web uygulamaları",
      "* ve API'lerin geliştirilmesinde büyük bir deneyime sahiptir. Backend tarafında,",
      "* veritabanı yönetimi, sunucu yönetimi ve veri işleme gibi konularda uzmanlık düzeyindedir.",
      "*",
      "* API'lerin tasarımı ve geliştirilmesi konusunda da yeteneklidir.",
      "* API tabanlı sistemlerin kurulması, API entegrasyonları",
      "* ve veri alışverişi gibi konularda geniş bir bilgi birikimine sahiptir.",
      "* Ayrıca, RESTful ve GraphQL gibi API mimarilerine hakimdir ve projelerin",
      "* performansını optimize etmek için en iyi uygulamaları takip etmektedir.",
      "*",
      "* Ayşe Ferda Yılmaz, Node.js, API'ler ve backend mimarileri konusundaki uzmanlığıyla,",
      "* müşterilerine yenilikçi ve verimli çözümler sunmaktadır.",
      "* Teknolojik gelişmeleri takip ederek, güncel trendleri uygulayarak",
      "* ve en iyi uygulamaları kullanarak projelerin başarılı bir şekilde tamamlanmasını sağlamaktadır.",
      "*/",
      "",
      "",
    ],
  },
  "Zeynep Buse Tanca": {
    header: "Designer",
    img: "/tfc.png",
    link: "https://tfaplatform.com/",
    desciription: [
      `/**`,
      "* Zeynep Buse Tanca, grafik tasarım alanında öncü bir uzmandır ve geniş bir deneyime sahiptir.",
      "* Kendisi, oyun modelleme konusunda uzmanlık seviyesine sahiptir ve oyun içerisindeki",
      "* her türlü nesnenin modellemesini başarıyla gerçekleştirebilmektedir.",
      "*",
      "* Zeynep Buse Tanca, oyun endüstrisindeki en önde gelen modelleme araçlarını ustalıkla kullanmaktadır.",
      "* Bu araçlar arasında Maya, 3ds Max, ZBrush gibi sektörde yaygın olarak kullanılan",
      "* profesyonel yazılımlar bulunmaktadır. Zeynep Buse, bu yazılımları en üst düzeyde kullanarak",
      "* gerçekçi ve etkileyici oyun modelleri oluşturma konusunda uzmandır.",
      "*",
      "* Grafik tasarım alanında öne çıkan yetenekleri sayesinde Zeynep Buse Tanca,",
      "* müşterilerin oyun projelerinin vizyonunu anlayarak, onlara özgün",
      "* ve dikkat çekici modellemeler sunmaktadır. Yaratıcılığı,",
      "* teknik becerileri ve sektördeki en son trendleri takip etme konusundaki",
      "* tutkusuyla oyunların görsel açıdan başarılı bir şekilde tamamlanmasını sağlamaktadır.",
      "*/",
      "",
      "",
    ],
  },
  "Serkan Aksoy": {
    header: "Full Stack Blockchain Developer",
    img: "/tfc.png",
    link: "https://tfaplatform.com/",
    desciription: [
      `/**`,
      "* Serkan Aksoy, frontend UI/UX tasarımında uzmanlaşmış bir profesyoneldir.",
      "* Kendisi, Photoshop, Figma ve Adobe XD gibi programlarda derin bir uzmanlığa sahip olup,",
      "* bu araçları etkin bir şekilde kullanarak benzersiz ve kullanıcı dostu tasarımlar",
      "* oluşturma konusunda yeteneklidir.",
      "*",
      "* Frontend UI/UX tasarımında uzmanlaşmasıyla birlikte,",
      "* Serkan Aksoy, kullanıcı ihtiyaçlarını anlamak ve kullanıcı deneyimini",
      "* optimize etmek için güçlü bir yeteneğe sahiptir.",
      "* Müşterilerinin taleplerini anlayarak, modern ve estetik açıdan",
      "* çekici web arayüzleri tasarlamakta ve kullanıcıların kolaylıkla",
      "* etkileşime girebileceği kullanıcı deneyimleri sunmaktadır.",
      "*",
      "* Serkan Aksoy, grafik tasarım ve frontend UI/UX konularındaki",
      "* uzmanlığı ve deneyimiyle, müşterilerine özgün, estetik açıdan çekici",
      "* ve kullanıcı odaklı tasarımlar sunmaktadır. Güçlü teknik becerileri,",
      "* yaratıcılığı ve görsel algısıyla, projelerin başarılı",
      "* bir şekilde tamamlanmasına katkıda bulunmaktadır.",
      "*/",
      "",
      "",
    ],
  },
  "Veysel Yenilmez": {
    header: "AI Developer",
    img: "/tfc.png",
    link: "https://tfaplatform.com/",
    desciription: [
      `/**`,
      "* Veysel Yenilmez, Python ve yapay zeka alanında uzmanlaşmış bir profesyoneldir",
      "* ve ekibimizde liderlik rolünü üstlenecektir. Geniş bir deneyime sahip olan Veysel,",
      "* Python programlama dilinde derin bir bilgiye sahiptir.",
      "* ve yapay zeka konularında uzmanlaşmıştır.",
      "*",
      "* Yaratıcı ve yenilikçi bir yaklaşımla çalışan Veysel, yapay zeka projelerinde",
      "* çözüm odaklı stratejiler geliştirme ve uygulama konusunda yeteneklidir.",
      "* Veri analizi, makine öğrenimi ve derin öğrenme gibi alanlarda uzmanlık seviyesinde",
      "* bilgi ve deneyime sahip olan Veysel, karmaşık problemleri çözmek ve",
      "* verilerden anlamlı bilgiler çıkarmak için güçlü algoritmalar kullanmaktadır.",
      "*",
      "* Veysel Yenilmez, Python ve yapay zeka projelerindeki tecrübesiyle",
      "* müşterilerin ihtiyaçlarına uygun özelleştirilmiş çözümler sunmaktadır.",
      "* Yüksek kaliteli kodlama, veri analizi ve modelleme yetenekleriyle",
      "* projelerin başarılı bir şekilde tamamlanmasına katkıda bulunmaktadır.",
      "*/",
      "",
      "",
    ],
  },
};
